### ISSUE TITLE
ACC TRIGGER ENABLE

### ISSUE THREAD

**Issue by Mendilli2** [KerJoe/ORTD2662-Junk#4]
Hi @KerJoe, I am taking your code as reference to create my custom firmware on a pcb800099 board, everything works except the pin named ACC on pcb800099 board.Basicly when 12v aplied to this pin board switches to AV2 automaticly and when 12v is removed board switches back to previous input like vga,hdmi etc
 
It is said on internet this ACC pin is coınnected to pin101 (P5D7) of rtd2660 chip.

so I need to define pin101 as an input in the pcb header file and read if it is HIGH or LOW, let say every 2 seconds

İs it possible you can help me, my working source code is attached
[RTD2660-master.zip](https://github.com/user-attachments/files/17240865/RTD2660-master.zip)
![Screenshot_2024-09-24-23-27-52-664_com android chrome](https://github.com/user-attachments/assets/dcd5c612-9c39-4ccb-bad8-cfb67815b1f0)

In your code PIN101 seems to be backlight enable pin but in my working code backlight enable pin is PIN111 and it works that way

**Comment by KerJoe** [comment]
I suppose it should probably look like this:

```diff
diff --color '--color=auto' -r -c a/Core/code/Main.c b/Core/code/Main.c
*** a/Core/code/Main.c  2024-09-30 19:45:54.000000000 +0400
--- b/Core/code/Main.c  2024-10-03 17:55:25.937954643 +0400
***************
*** 159,171 ****
  {
      CMainSystemInitial();
      CUartSendString("Begin...\n");
      do
      {
          CMiscIspDebugProc();                                         
          CTimerHandler();
          CKeyHandler();
          CModeHandler();
!         COsdHandler(); 
      }while(_TRUE);
  }
  
--- 159,187 ----
  {
      CMainSystemInitial();
      CUartSendString("Begin...\n");
+     unsigned char checkTime = 0; // Debounce timer
+     char prevInput = -1; // Previously selected input
      do
      {
          CMiscIspDebugProc();                                         
          CTimerHandler();
          CKeyHandler();
          CModeHandler();
!         COsdHandler();
! 
!         if (checkTime++ == 255)
!         {
!             if (ACC_PORT) // If P5D7 High
!             {
!                 prevInput = _GET_INPUT_SOURCE();
!                 _SET_INPUT_SOURCE(_SOURCE_VIDEO_AV);
!             }
!             else if (prevInput != -1) // If input was changed and P5D7 Low
!             {
!                 _SET_INPUT_SOURCE(prevInput)
!                 prevInput = -1;
!             }
!         }
      }while(_TRUE);
  }
  
diff --color '--color=auto' -r -c a/PCB/PCB800099.h b/PCB/PCB800099.h
*** a/PCB/PCB800099.h   2024-09-30 19:44:44.000000000 +0400
--- b/PCB/PCB800099.h   2024-10-03 17:34:58.812017537 +0400
***************
*** 196,202 ****
  #define _PIN_98                                                               (2 & 0x03)      // 0 ~ 3 (0: P5D4i, 1: P5D4o<open-drain>, 2: P5D4o<push-pull>, 3: PWM2)
  #define _PIN_99                                                               (2 & 0x07)      // 0 ~ 5 (0: P5D5i, 1: P5D5o<open-drain>, 2: P5D5o<push-pull>, 3: PWM3, 4: TCON[6], 5: TCON[11])
  #define _PIN_100                                                              (4 & 0x07)      // 0 ~ 5 (0: P5D6i, 1: P5D6o<open-drain>, 2: P5D6o<push-pull>, 3: PWM4, 4: TCON[3], 5: TCON[12])
! #define _PIN_101                                                              (2 & 0x07)      // 0 ~ 4 (0: P5D7i, 1: P5D7o<open-drain>, 2: P5D7o<push-pull>, 3: PWM5, 4: TCON[0])
  #define _PIN_102                                                              (6 & 0x07)      // 0 ~ 6 (0: P7D6i, 1: P7D6o<open-drain>, 2: P7D6o<push-pull>, 3: PWM0, 4: SD3, 5: SPDIF3, 6: TCON[10])
  #define _PIN_103                                                              (6 & 0x07)      // 0 ~ 7 (0: P7D5i, 1: P7D5o<open-drain>, 2: P7D5o<push-pull>, 3: PWM1, 4: SD2, 5: SPDIF2, 6: TCON[8], 7: IICSCL)
  #define _PIN_104                                                              (5 & 0x07)      // 0 ~ 7 (0: P7D4i, 1: P7D4o<open-drain>, 2: P7D4o<push-pull>, 3: SD1, 4: IRQ, 5: TCON[5], 6: SPDIF1, 7: IICSDA)
--- 196,202 ----
  #define _PIN_98                                                               (2 & 0x03)      // 0 ~ 3 (0: P5D4i, 1: P5D4o<open-drain>, 2: P5D4o<push-pull>, 3: PWM2)
  #define _PIN_99                                                               (2 & 0x07)      // 0 ~ 5 (0: P5D5i, 1: P5D5o<open-drain>, 2: P5D5o<push-pull>, 3: PWM3, 4: TCON[6], 5: TCON[11])
  #define _PIN_100                                                              (4 & 0x07)      // 0 ~ 5 (0: P5D6i, 1: P5D6o<open-drain>, 2: P5D6o<push-pull>, 3: PWM4, 4: TCON[3], 5: TCON[12])
! #define _PIN_101                                                              (0 & 0x07)      // 0 ~ 4 (0: P5D7i, 1: P5D7o<open-drain>, 2: P5D7o<push-pull>, 3: PWM5, 4: TCON[0])
  #define _PIN_102                                                              (6 & 0x07)      // 0 ~ 6 (0: P7D6i, 1: P7D6o<open-drain>, 2: P7D6o<push-pull>, 3: PWM0, 4: SD3, 5: SPDIF3, 6: TCON[10])
  #define _PIN_103                                                              (6 & 0x07)      // 0 ~ 7 (0: P7D5i, 1: P7D5o<open-drain>, 2: P7D5o<push-pull>, 3: PWM1, 4: SD2, 5: SPDIF2, 6: TCON[8], 7: IICSCL)
  #define _PIN_104                                                              (5 & 0x07)      // 0 ~ 7 (0: P7D4i, 1: P7D4o<open-drain>, 2: P7D4o<push-pull>, 3: SD1, 4: IRQ, 5: TCON[5], 6: SPDIF1, 7: IICSDA)
***************
*** 241,247 ****
  #define LR_UD_OFF                                  0
  #define LR_UD_PWR                                      (_MCU_PORT54)//= P3^7;
  
! #define ACC_PIN                                        _PIN_101
  
  #define bD0                         (_NON_CONNECT_PIN)
  #define bD1                         (_NON_CONNECT_PIN)
--- 241,248 ----
  #define LR_UD_OFF                                  0
  #define LR_UD_PWR                                      (_MCU_PORT54)//= P3^7;
  
! #define ACC_PIN                                        (_PIN_101)
! #define ACC_PORT                    (_MCU_PORT57)
  
  #define bD0                         (_NON_CONNECT_PIN)
  #define bD1                         (_NON_CONNECT_PIN)

```

**Comment by Mendilli2** [comment]
#define ACC_PIN                                  (_PIN_101)
!#define ACC_PORT                    (_MCU_PORT57)

You use ACC_PORT in main.c but I can not see where is ACC_PIN used

**Comment by Mendilli2** [comment]
I get this compile error
![error](https://github.com/user-attachments/assets/bf00548f-f869-4897-aaf0-4593276ea5c8)

**Comment by KerJoe** [comment]
I think Keil only allows variable declaration at the start of the function, move the variables up:
```diff
*** a/Core/code/Main.c  2024-09-30 19:45:54.000000000 +0400
--- b/Core/code/Main.c  2024-10-03 19:26:39.722124259 +0400
***************
*** 157,162 ****
--- 157,166 ----
  */
  void main(void)
  {
+     char checkTime;
+     char prevInput;
+     checkTime = 0;
+     prevInput = -1
      CMainSystemInitial();
      CUartSendString("Begin...\n");
      do
***************
```

**Comment by Mendilli2** [comment]
Thank you vrry much, code compiled without error but accidentsaly I have burnt my pcb800099 board and could test it, I am waitüng new board to arrive

Last 2 questions

1) isn't it necessary for counter to reset at some point like

if (checkTime++ == 255)
{
       checkTime=0; // reset counter
        if (ACC_PORT) // If P5D7 HIGH
        .........

2) As far as I know in c++ to set a pin  as INPUT first it must be set to 1(HIGH) then read it  like

PIN = 1; // Set pin to high, set pin as INPUT
var READ = PIN; // Read pin and assign the result to READ variable

I think changing 2x007 to 0x007 in pin definition sets the pin as INPUT so there is no need to set it to 1(HIGH)  extra is that right?

**Comment by KerJoe** [comment]
> You use ACC_PORT in main.c but I can not see where is ACC_PIN used

ACC_PIN is not used anywhere, it's only used as context for `diff`.

> isn't it necessary for counter to reset at some point like
> if (checkTime++ == 255)
> {
> checkTime=0; // reset counter
> if (ACC_PORT) // If P5D7 HIGH
>.........

Yes, if the variable type or the check value were to change, it should be reset to 0. But because the variable is an `unsigned char` it will wrap-around by itself.

> As far as I know in c++ to set a pin as INPUT first it must be set to 1(HIGH) then read it like
> PIN = 1; // Set pin to high, set pin as INPUT
> var READ = PIN; // Read pin and assign the result to READ variable

First of all, the code is in pure C. Second, the pin mode is set by `PIN_SHARE` group of registers and the value of 0 coresponds to the input mode, the code that sets it is in `CMiscSetPinShare` function. Third, whether the reading of the pin register results in it's input or output value is determined by the `PORT_READ_CTRL` register, which is set in `CMcuInitial` to read input state from all ports but the third one.

**Comment by Mendilli2** [comment]
Thank you very much, I am totally noob on coding so everything is very
diffucult for me, you have been very kind and helpfull, when I get the new
board I will share the result, and may be you can help me how to change the
startup logo with a custom one, after all your support I am ashemed to ask
for it but I have been trying to change it for nearly a month

4 Eki 2024 Cum 08:28 tarihinde KerJoe ***@***.***> şunu yazdı:

**Comment by KerJoe** [comment]
You are welcome, but, I hate to say it, I don't think this is the right place to discuss working on the leaked firmware I'd much rather see people working on my source code than trying to work around the leaked one.

**Comment by Mendilli2** [comment]
I  see and totally agree with you, I have tried to compile your code on a
windows 10 using minigw but it always throws an error abut a file can not
be found in sys folder which does not exist

4 Eki 2024 Cum 09:00 tarihinde KerJoe ***@***.***> şunu yazdı:

**Comment by KerJoe** [comment]
I have explained how to setup the environment on windows in this issue:
https://github.com/KerJoe/ORTD2662/issues/3#issuecomment-2308140187

**Comment by KerJoe** [comment]
The firmware is compiled similarly:
```
pacman -S sdcc
make firmware
```

**Comment by Mendilli2** [comment]
Thanks, I will try it as soos as posdible

4 Eki 2024 Cum 10:25 tarihinde KerJoe ***@***.***> şunu yazdı:

**Comment by Mendilli2** [comment]
sorry man but msys2 does not install sdcc (It successfully installed other packages like git vs)
![sdcc](https://github.com/user-attachments/assets/5e20b551-c94f-47a0-b807-50e7f3a2e36a)

**Comment by KerJoe** [comment]
Oh, it's not in the repos, that complicates things...
Can you try installing `mingw` and `sdcc` natively and running `make firmware` in `cmd`?

**Comment by Mendilli2** [comment]
Sure I will try and let you know

4 Eki 2024 Cum 18:31 tarihinde KerJoe ***@***.***> şunu yazdı:

**Comment by Mendilli2** [comment]
I have found a mingw version with built in sdcc but I could not make it work

https://www.teco.edu/~winkler/index.html

**Comment by KerJoe** [comment]
I meant use [mingw's gnu utilities](https://github.com/niXman/mingw-builds-binaries/releases/download/14.2.0-rt_v12-rev0/x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0.7z) and [stabdalone sdcc toolchain](https://sourceforge.net/projects/sdcc/files/sdcc-win64/4.4.0/sdcc-4.4.0-rc3-x64-setup.exe/download).

**Comment by Mendilli2** [comment]
I dont know if I did it right compiling started and gave the same erroe

gcc ./core/misc.c -I. -MMD -ggdb3 -o output_native/misc.o -c
gcc ./core/i2c_native_iface.c -I. -MMD -ggdb3 -o output_native/i2c_native_iface.o -c
./core/i2c_native_iface.c:98:23: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>
                       ^
compilation terminated.
Makefile:47: recipe for target 'output_native/i2c_native_iface.o' failed
make: *** [output_native/i2c_native_iface.o] Error 1

**Comment by KerJoe** [comment]
Use `make firmware`, not just `make`

**Comment by Mendilli2** [comment]
Ok compiled without error and created a firmware.bin file but it is only 32KB size

**Comment by Mendilli2** [comment]
Ok compiled without error and created a firmware.bin file but it is only
32KB size

4 Eki 2024 Cum 22:32 tarihinde KerJoe ***@***.***> şunu yazdı:

**Comment by KerJoe** [comment]
Well, that's all there is...

**Comment by Mendilli2** [comment]
> I suppose it should probably look like this:
> 
> ```diff
> diff --color '--color=auto' -r -c a/Core/code/Main.c b/Core/code/Main.c
> *** a/Core/code/Main.c  2024-09-30 19:45:54.000000000 +0400
> --- b/Core/code/Main.c  2024-10-03 17:55:25.937954643 +0400
> ***************
> *** 159,171 ****
>   {
>       CMainSystemInitial();
>       CUartSendString("Begin...\n");
>       do
>       {
>           CMiscIspDebugProc();                                         
>           CTimerHandler();
>           CKeyHandler();
>           CModeHandler();
> !         COsdHandler(); 
>       }while(_TRUE);
>   }
>   
> --- 159,187 ----
>   {
>       CMainSystemInitial();
>       CUartSendString("Begin...\n");
> +     unsigned char checkTime = 0; // Debounce timer
> +     char prevInput = -1; // Previously selected input
>       do
>       {
>           CMiscIspDebugProc();                                         
>           CTimerHandler();
>           CKeyHandler();
>           CModeHandler();
> !         COsdHandler();
> ! 
> !         if (checkTime++ == 255)
> !         {
> !             if (ACC_PORT) // If P5D7 High
> !             {
> !                 prevInput = _GET_INPUT_SOURCE();
> !                 _SET_INPUT_SOURCE(_SOURCE_VIDEO_AV);
> !             }
> !             else if (prevInput != -1) // If input was changed and P5D7 Low
> !             {
> !                 _SET_INPUT_SOURCE(prevInput)
> !                 prevInput = -1;
> !             }
> !         }
>       }while(_TRUE);
>   }
>   
> diff --color '--color=auto' -r -c a/PCB/PCB800099.h b/PCB/PCB800099.h
> *** a/PCB/PCB800099.h   2024-09-30 19:44:44.000000000 +0400
> --- b/PCB/PCB800099.h   2024-10-03 17:34:58.812017537 +0400
> ***************
> *** 196,202 ****
>   #define _PIN_98                                                               (2 & 0x03)      // 0 ~ 3 (0: P5D4i, 1: P5D4o<open-drain>, 2: P5D4o<push-pull>, 3: PWM2)
>   #define _PIN_99                                                               (2 & 0x07)      // 0 ~ 5 (0: P5D5i, 1: P5D5o<open-drain>, 2: P5D5o<push-pull>, 3: PWM3, 4: TCON[6], 5: TCON[11])
>   #define _PIN_100                                                              (4 & 0x07)      // 0 ~ 5 (0: P5D6i, 1: P5D6o<open-drain>, 2: P5D6o<push-pull>, 3: PWM4, 4: TCON[3], 5: TCON[12])
> ! #define _PIN_101                                                              (2 & 0x07)      // 0 ~ 4 (0: P5D7i, 1: P5D7o<open-drain>, 2: P5D7o<push-pull>, 3: PWM5, 4: TCON[0])
>   #define _PIN_102                                                              (6 & 0x07)      // 0 ~ 6 (0: P7D6i, 1: P7D6o<open-drain>, 2: P7D6o<push-pull>, 3: PWM0, 4: SD3, 5: SPDIF3, 6: TCON[10])
>   #define _PIN_103                                                              (6 & 0x07)      // 0 ~ 7 (0: P7D5i, 1: P7D5o<open-drain>, 2: P7D5o<push-pull>, 3: PWM1, 4: SD2, 5: SPDIF2, 6: TCON[8], 7: IICSCL)
>   #define _PIN_104                                                              (5 & 0x07)      // 0 ~ 7 (0: P7D4i, 1: P7D4o<open-drain>, 2: P7D4o<push-pull>, 3: SD1, 4: IRQ, 5: TCON[5], 6: SPDIF1, 7: IICSDA)
> --- 196,202 ----
>   #define _PIN_98                                                               (2 & 0x03)      // 0 ~ 3 (0: P5D4i, 1: P5D4o<open-drain>, 2: P5D4o<push-pull>, 3: PWM2)
>   #define _PIN_99                                                               (2 & 0x07)      // 0 ~ 5 (0: P5D5i, 1: P5D5o<open-drain>, 2: P5D5o<push-pull>, 3: PWM3, 4: TCON[6], 5: TCON[11])
>   #define _PIN_100                                                              (4 & 0x07)      // 0 ~ 5 (0: P5D6i, 1: P5D6o<open-drain>, 2: P5D6o<push-pull>, 3: PWM4, 4: TCON[3], 5: TCON[12])
> ! #define _PIN_101                                                              (0 & 0x07)      // 0 ~ 4 (0: P5D7i, 1: P5D7o<open-drain>, 2: P5D7o<push-pull>, 3: PWM5, 4: TCON[0])
>   #define _PIN_102                                                              (6 & 0x07)      // 0 ~ 6 (0: P7D6i, 1: P7D6o<open-drain>, 2: P7D6o<push-pull>, 3: PWM0, 4: SD3, 5: SPDIF3, 6: TCON[10])
>   #define _PIN_103                                                              (6 & 0x07)      // 0 ~ 7 (0: P7D5i, 1: P7D5o<open-drain>, 2: P7D5o<push-pull>, 3: PWM1, 4: SD2, 5: SPDIF2, 6: TCON[8], 7: IICSCL)
>   #define _PIN_104                                                              (5 & 0x07)      // 0 ~ 7 (0: P7D4i, 1: P7D4o<open-drain>, 2: P7D4o<push-pull>, 3: SD1, 4: IRQ, 5: TCON[5], 6: SPDIF1, 7: IICSDA)
> ***************
> *** 241,247 ****
>   #define LR_UD_OFF                                  0
>   #define LR_UD_PWR                                      (_MCU_PORT54)//= P3^7;
>   
> ! #define ACC_PIN                                        _PIN_101
>   
>   #define bD0                         (_NON_CONNECT_PIN)
>   #define bD1                         (_NON_CONNECT_PIN)
> --- 241,248 ----
>   #define LR_UD_OFF                                  0
>   #define LR_UD_PWR                                      (_MCU_PORT54)//= P3^7;
>   
> ! #define ACC_PIN                                        (_PIN_101)
> ! #define ACC_PORT                    (_MCU_PORT57)
>   
>   #define bD0                         (_NON_CONNECT_PIN)
>   #define bD1                         (_NON_CONNECT_PIN)
> ```

ACC_PIN does not seem to work, I think pin number is wrong, ı tried to define the pin number using a buzzer between the acc pin and the rtd2660 legs, nothing came out, do you have any idea how to define correct pin number

**Comment by KerJoe** [comment]
ACC input goes through a transistor switch. Test if voltage changes on pin 101 when the 12V are applied to ACC input. You may also have to invert the condition (`if (!ACC_PORT) // If P5D7 Low`), due to the inversion from the transistor switch.

**Comment by Mendilli2** [comment]
Also when compiling, unsigned char or char is not accepted, I had to remove
previnput and set the checktime variable as int, then compile succeded

5 Eki 2024 Cmt 13:50 tarihinde KerJoe ***@***.***> şunu yazdı:

**Comment by Mendilli2** [comment]
I measured acc pin with a multimeter, normally it reads 0 v but when I
apply 12v then it reads 12v (when use this board with a generic firmware
acc pin just works)

5 Eki 2024 Cmt 15:28 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by KerJoe** [comment]
I mean check the voltage on RTD2662.

**Comment by KerJoe** [comment]
Honestly, unless you can debug the leaked source yourself, I think you are better off just ripping the ACC code from some other firmware.

**Comment by coucouillu** [comment]
Hi @Mendilli2 
I am also working on a custom firmware for pcb800099.

Please use your dead board to check where the ACC pin of the board is connected physically to which pin of the RTD.

**Comment by coucouillu** [comment]
> Hi @Mendilli2 I am also working on a custom firmware for pcb800099.
> 
> Please use your dead board to check where the ACC pin of the board is connected physically to which pin of the RTD.

I have just check from my pcb800099 board with generic firmware where ACC pin works).
The ACC pin of the board is connected to the pin 101 of the RTD (GPIO/PWM5/TCON[0])

ACC pin from pcb800099 LOW= pin 101 HIGH=nothing
ACC pin from pcb800099 HIGH= pin 101 LOW=activate AV2

**Comment by Mendilli2** [comment]
Thank you for you support can you please tell me how to physically check
it, do you mean by eye or by a buzzer also can you tell the type of your
board please, is t a green or blue board

12 Eki 2024 Cmt 18:41 tarihinde coucouillu ***@***.***> şunu
yazdı:

**Comment by Mendilli2** [comment]
12 Eki 2024 Cmt 19:56 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
One last thing, can you access pin 54 in source code, if so is it possible
tı share the code piece please

12 Eki 2024 Cmt 19:56 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
> > Hi @Mendilli2 I am also working on a custom firmware for pcb800099.
> > Please use your dead board to check where the ACC pin of the board is connected physically to which pin of the RTD.
> 
> I have just check from my pcb800099 board with generic firmware where ACC pin works). The ACC pin of the board is connected to the pin 101 of the RTD (GPIO/PWM5/TCON[0])
> 
> ACC pin from pcb800099 LOW= pin 101 HIGH=nothing ACC pin from pcb800099 HIGH= pin 101 LOW=activate AV2

Hi, in your mail message you said acc pin is connected to pin 54, but here you say it is pin 101, I dont understand

**Comment by coucouillu** [comment]
> > > Hi @Mendilli2 I am also working on a custom firmware for pcb800099.
> > > Please use your dead board to check where the ACC pin of the board is connected physically to which pin of the RTD.
> > 
> > 
> > I have just check from my pcb800099 board with generic firmware where ACC pin works). The ACC pin of the board is connected to the pin 101 of the RTD (GPIO/PWM5/TCON[0])
> > ACC pin from pcb800099 LOW= pin 101 HIGH=nothing ACC pin from pcb800099 HIGH= pin 101 LOW=activate AV2
> 
> Hi, in your mail message you said acc pin is connected to pin 54, but here you say it is pin 101, I dont understand

I edited my message, thinking you still have not read it yet you semmes that you received an email from my first editon of message. Sorry for that

**Comment by coucouillu** [comment]
@Mendilli2,
I have the blue one. I did my test with a multimeter. 
![17287647421462817354155449568319](https://github.com/user-attachments/assets/f29e641b-c9a3-4653-bae7-e47f142998e0)

**Comment by Mendilli2** [comment]
How about the source code, have you ever managed to make acc pin work, can
you help me with that

12 Eki 2024 Cmt 23:28 tarihinde coucouillu ***@***.***> şunu
yazdı:

**Comment by coucouillu** [comment]
> How about the source code, have you ever managed to make acc pin work, can you help me with that

I will try to have a look but not sure to find.

**Comment by Mendilli2** [comment]
Ok, some progress here, the acc pin number is _PIN_101 or _MCU_PORT57 indeed, By default it is HIGH because of internal pullup, when you apply power it goes LOW, problem was feeding this pin with 5v. It seems 5v is not enough to change the state of the pin to LOW, when I applied 12v it began to react ( I ialtered the source change button code of the keyboard, I altered it to stop changing source when 12v aplied to acc pin. so when I presssed source change button I saw source is changed normally but when I applied 12v to acc pin source change button stopped working)

I am now working on to implement it into the main loop, but I could not make it work yet

**Comment by Mendilli2** [comment]
Not perfect but this seems to work

PCB800099.h file

#define _PIN_101		(0 & 0x07)	// 0 ~ 4 (0: P5D7i, 1: P5D7o<open-drain>, 2: P5D7o<push-pull>, 3: PWM5, 4: TCON[0])
#define _ACC_PIN 					 (_MCU_PORT57)

--------------------------------------------------------------------------------------------------------------------------------------

Main.h file

// Function Prototypes
//--------------------------------------------------
void CMainUserInitial();
void CMainSystemInitial(void);
void ACCChangeSource(void);
void DbgLed(unsigned char ucCount);

---------------------------------------------------------------------------------------------------------------------------------------

Main.c file
void main(void)
{
    CMainSystemInitial();
    CUartSendString("Begin...\n");
    do
    {
        CMiscIspDebugProc();                                         
        CTimerHandler();
        CKeyHandler();
        CModeHandler();
        COsdHandler(); 
	ACCChangeSource();
    }while(_TRUE);
}

void ACCChangeSource(void)
{
	if (!_ACC_PIN && _GET_INPUT_SOURCE() == _SOURCE_VGA)
	{
		switch(_GET_INPUT_SOURCE())
		{
			case _SOURCE_VGA:			_SET_INPUT_SOURCE(_SOURCE_VIDEO_SV);
			default: break;
		}
		COsdDispOsdTimerEvent();              
		ucOsdEventMsg = _CHANGE_SOURCE_MSG;
	}
    else if (_ACC_PIN && _GET_INPUT_SOURCE() == _SOURCE_VIDEO_SV)
	{
		switch(_GET_INPUT_SOURCE())
		{
			case _SOURCE_VIDEO_SV:			_SET_INPUT_SOURCE(_SOURCE_VGA);
			default: break;
		}
		COsdDispOsdTimerEvent();              
		ucOsdEventMsg = _CHANGE_SOURCE_MSG;
	}
}

**Comment by coucouillu** [comment]
> Not perfect but this seems to work

I have tested your code and it works also on my side. Weel done. But I will not keep is as I am looking for debug mode in order to help custom software development and I guess that the PIN_101 is used for (not sure but I am investigating.)

**Comment by Mendilli2** [comment]
Thanks, my next target is having a custom startup logo, I can activate the default logo but can not change it with a different logo, do you have any idea how to do that

**Comment by coucouillu** [comment]
[LOGO]
@Mendilli2 
Could depend of the source code you are using. Some source code are linked to a picture as logo. other a leters diplayed. I already made some tests an succed in displaying soft onboarded Logo for both.
Just enable ` #define _LOGO_ENABLE _ENABLE` in your 'Pcb_RTDxxxxD_LCDTV_DEMO_PCBy.h' file and let see your default LOGO (letters or  a picture?).
To continue exchange, let do it on Discord, Whatsapp etc... because @KerJoe do not want us to talk about potential leaked code here (and he is right).  Feel free to share your contact.

On my side I try to use UART to accelerate/ease further developement

**Comment by Mendilli2** [comment]
Discord is closed in my country, do you mind using e-mail.If you share you
e mail, I send you my source code, mine is
***@***.***

13 Eki 2024 Paz 19:21 tarihinde coucouillu ***@***.***> şunu
yazdı:

**Comment by coucouillu** [comment]
@Mendilli2 your email has been censured by github

**Comment by Mendilli2** [comment]
mendilli2 g m a i l

**Comment by Mendilli2** [comment]
Ok, some progress here, the acc pin number is _PIN_101 or _MCU_PORT57 indeed, By default it is HIGH because of internal pullup, when you apply power it goes LOW, problem was feeding this pin with 5v. It seems 5v is not enough to change the state of the pin to LOW (use 12v)

Not perfect but this seems to work

PCB800099.h file
#define _PIN_101 (0 & 0x07) // 0 ~ 4 (0: P5D7i, 1: P5D7o, 2: P5D7o, 3: PWM5, 4: TCON[0]) //(change this line)

#define _ACC_PIN (_MCU_PORT57) // (add this line)

Main.h file
void CMainUserInitial();
void CMainSystemInitial(void);
void ACCChangeSource(void); //(add this line)
void DbgLed(unsigned char ucCount);

Main.c file
void main(void)
{
CMainSystemInitial();
CUartSendString("Begin...\n");
do
{
CMiscIspDebugProc();
CTimerHandler();
CKeyHandler();
CModeHandler();
COsdHandler();
ACCChangeSource(); //(add this line)
}while(_TRUE);
}

void ACCChangeSource(void) { // (add this function)

if (!_ACC_PIN && _GET_INPUT_SOURCE() == _SOURCE_VGA)
{
switch(_GET_INPUT_SOURCE())
{
case _SOURCE_VGA: _SET_INPUT_SOURCE(_SOURCE_VIDEO_SV);
default: break;
}
COsdDispOsdTimerEvent();
ucOsdEventMsg = _CHANGE_SOURCE_MSG;
}
else if (_ACC_PIN && _GET_INPUT_SOURCE() == _SOURCE_VIDEO_SV)
{
switch(_GET_INPUT_SOURCE())
{
case _SOURCE_VIDEO_SV: _SET_INPUT_SOURCE(_SOURCE_VGA);
default: break;
}
COsdDispOsdTimerEvent();
ucOsdEventMsg = _CHANGE_SOURCE_MSG;
}
}
